### ISSUE TITLE
Monitoring ETL Flows with Grafana - File statistics Publishing to Prometheus is not working in SI 1.1.0

### ISSUE THREAD

**Issue by ug205** [wso2/micro-integrator#3728]
### Description

We are observing the following error when trying the monitor ETL Flows with Grafana documentation [1]. This is specifically for file statistics, and observed due to a  security fix that included guava dependency version bump.
```
Exception in thread "Siddhi-Renamefile_siddhi-executor-thread-2" java.lang.NoClassDefFoundError: com/google/common/base/Stopwatch
at io.siddhi.extension.io.file.processors.FileProcessor.lambda$new$3(FileProcessor.java:90)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.ClassNotFoundException: com.google.common.base.Stopwatch cannot be found by siddhi-io-file_2.0.10.28
at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:448)
at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:361)
at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:353)
at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:161)
at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
... 4 more
```

[1]. https://ei.docs.wso2.com/en/latest/streaming-integrator/admin/setting-up-grafana-dashboards/

### Steps to Reproduce

Steps to Reproduce;

Download and Install Grafana and Prometheus.
Configure Prometheus using the documentation [1] and start the Prometheus server.
Start Grafana server and configure using the documentation [1].
Enable metrics and Prometheus metrics in SI deployment.yaml using the documentation [1].
Create a siddhi file with file source and sink.
Start the SI server and observe when the siddhi application is deployed, the above mentioned error is printed.

[1].https://ei.docs.wso2.com/en/latest/streaming-integrator/admin/setting-up-grafana-dashboards/

### Affected Component

SI

### Version

1.1.0
