### ISSUE TITLE
Kafka inbound EP (connector) does not work

### ISSUE THREAD

**Issue by abeykoon** [wso2/micro-integrator#2160]
**Description:**

Followed the instructions at [1] to setup Apache Kafka with WSO2 EI. 
It does not poll messages, but keep throwing below error 

```
[2021-03-17 14:26:33,518] ERROR {TaskQuartzJobAdapter} - Error in executing task: org.apache.kafka.clients.consumer.KafkaConsumer.poll(Ljava/time/Duration;)Lorg/apache/kafka/clients/consumer/ConsumerRecords; java.lang.NoSuchMethodError: org.apache.kafka.clients.consumer.KafkaConsumer.poll(Ljava/time/Duration;)Lorg/apache/kafka/clients/consumer/ConsumerRecords;
	at org.wso2.carbon.inbound.kafka.KafkaMessageConsumer.consumeKafkaRecords(KafkaMessageConsumer.java:97)
	at org.wso2.carbon.inbound.kafka.KafkaMessageConsumer.poll(KafkaMessageConsumer.java:354)
	at org.wso2.carbon.inbound.endpoint.protocol.generic.GenericTask.taskExecute(GenericTask.java:40)
	at org.wso2.carbon.inbound.endpoint.common.InboundTask.execute(InboundTask.java:49)
	at org.wso2.micro.integrator.mediation.ntask.NTaskAdapter.execute(NTaskAdapter.java:105)
	at org.wso2.micro.integrator.ntask.core.impl.TaskQuartzJobAdapter.execute(TaskQuartzJobAdapter.java:63)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:213)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

Apache Kafka version used : kafka_2.12-1.0.0 (recommended on the doc )

[1]. https://ei.docs.wso2.com/en/latest/micro-integrator/references/connectors/kafka-connector/kafka-inbound-endpoint-example/

**Comment by abeykoon** [comment]
I have tested this. Seems even if documentation recommends  `kafka_2.12-1.0.0`, the inbound EP works with `kafka_2.11-2.2.1` (Released Jun 1, 2019) onwards. There is an API change in the kafka client.

**Comment by abeykoon** [comment]
So it will make sense to update the recommended version to `kafka_2.11-2.2.1` in documentation.

**Comment by abeykoon** [comment]
The list of libraries should be updated. 

kafka_2.11-2.2.1
kafka-clients-2.2.1
metrics-core-2.2.0
scala-library-2.11.12
zkclient-0.11
zookeeper-3.4.13

We can get them from <Kafka_home>/lib folder.

**Comment by Nirothipan** [comment]
Fixed with https://github.com/wso2/docs-ei/pull/2769
